### ISSUE TITLE
Crear un componente que sea editable

### ISSUE THREAD

**Issue by Maik3345** [vtex-apps/store-theme#88]
Hola! Estoy intentando crear un componente con un comportamiento peculiar, quiero que este componente permita cargar otros componentes, algo como un gestor de componentes. algo simple y que ya me funciono. pero cuando importo cada uno de los componentes encuentro que estos no son editables

He echo el análisis del proceso para poder editar un componente en el StoreFront y llegue al proyecto (https://github.com/vtex-apps/render-runtime) donde se encuentra toda esta lógica que permite editar un componente, mi pregunta es. como puedo yo replicar este proceso para que los componentes que se carguen sean editables como cuando son cargados por medio del ExtensionPoint en el pages.json del dreamstore.

**Comment by brunojdo** [comment]
Hi @Maik3345 I will answer your question in English, ok? 

Do you want to add an app (component) using Storefront, right? Previously, this was a feature that we have but after our major refactoring, this isn't available yet. We still working in this feature to adapt to the new UI/UX of Pages. I do not know if that answers your doubts.

**Comment by Maik3345** [comment]
Hola @brunojdo Gracias.

Si, entiendo que por ahora este comportamiento no se tiene, pero seria bueno poder hacerlo. ya que eso provee mayor dinamismo a la hora de editar componentes.

**Comment by brunojdo** [comment]
Yeah, I agree. We have this feature in the roadmap.
